name: Generate feature candidate

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Generate tag from a rc'
        required: true
        default: 'rc/0.0.0'


jobs:
  release:
    name:  Create a tag
    environment:
      name: zappts
#      url: ${{ steps.step_id.outputs.url_output }}
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<steff.vasem@gmail.com"
        git checkout rc/"${{ github.event.inputs.tag }}"
        git tag v"${{ github.event.inputs.tag }}"
        git push --set-upstream origin v"${{ github.event.inputs.tag }}"
        git push origin --delete rc/"${{ github.event.inputs.tag }}"