name: Creating tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Generate tag from a rc'
        required: true
        default: '0.0.0'


jobs:
  tag:
    name:  Create a tag
    environment:
      name: zappts
#      url: ${{ steps.step_id.outputs.url_output }}
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<steff.vasem@gmail.com"
        git checkout rc/"${{ github.event.inputs.tag }}"
        git tag v"${{ github.event.inputs.tag }}"
        git push --set-upstream origin v"${{ github.event.inputs.tag }}"
        git push origin --delete rc/"${{ github.event.inputs.tag }}"
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v"${{ github.event.inputs.tag }}
          release_name: v"${{ github.event.inputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false