name: Generate feature candidate

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Input new version'
        required: true
        default: '0.0.0'


jobs:
  release:
    needs: zappts
    name: Feature ready
    environment:
      name: zappts
#      url: ${{ steps.step_id.outputs.url_output }}
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<steff.vasem@gmail.com"
        git checkout -b rc/"${{ github.event.inputs.version }}
        git push --set-upstream origin rc/"${{ github.event.inputs.version }}
#        git push origin --delete feature/testeque foi acionada na trigger, dar checkou nela e criar a partir dela a nova. 
#Realizar estágio onde valida se está ok no environemnts anteriores 
# Só realizar algo se a branch for igual feature/**



##deletar versão publicada em dev, qa e zappts
#      "${{ github.event.inputs.message }}
#      github.event.inputs.use-emoji == 'true' 
#      ${{ github.event.inputs.name }}"
